### ISSUE TITLE
Changes request

### ISSUE THREAD

**Issue by glebfox** [Gamer08YT/jmix-swagger-ui-addon#5]
I've made a brief review and have a few questions/suggestions:

1. Do you really need `@NpmPackage(value = "jquery", version = "1.9.1")` dependancy? Adding the `jquery` dependency globally may lead to conflicts, as it is a common dependency for JS libraries and they require different versions. It's better to use `noConflict` version, see example in the [PivotTable](https://github.com/jmix-framework/jmix/blob/master/jmix-pivottable/pivottable-flowui-kit/src/main/resources/META-INF/frontend/src/pivot-table/jmix-pivot-table.js) component. 

Currently, I see that `jquery` is needed just for the following code which may be replaced:

```
// Clear Render Container.
$(this._domElement).empty();
```

If `jquery` isn't needed for the correct functionality of `swagger-ui`, I'd recommend removing this dependency.

2. It's better to move `swagger-ui.xsd` from the `frontend` folder to the root of the resources, i.e. to the same place where `menu.xml` is located.

**Comment by Gamer08YT** [comment]
Hello Gleb,

thanks for your feedback.

The JQuery is really not necessary, I guess I was a bit lazy to use my brain :)

I moved the descriptor for the component to the menu.xml directory.

https://github.com/Gamer08YT/jmix-swagger-ui-addon/releases/tag/1.1.4

Regards
