### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by knstvk** [Gamer08YT/jmix-swagger-ui-addon#6]
Please improve the README:
- Add information about add-on versions and instruction for manual installation like [this one](https://github.com/pbaris/jmix-multilingual-field?tab=readme-ov-file#installation).
- Remove `implementation 'de.bytestore:swagger-ui'`, it's not needed
- For Springdoc, perhaps add a version to coordinates (currently it is not included in BOM). 
- Mention that the add-on already provides a built-in view displaying the API (from what URL?).
- Write "Jmix" with first capital

**Comment by Gamer08YT** [comment]
README updated ;)

> * a version to coordinates

Can you tell me in more detail what you mean by that?

**Comment by knstvk** [comment]
> > * a version to coordinates
> 
> Can you tell me in more detail what you mean by that?

I mean the concrete Springdoc version. Perhaps it's OK to describe it as you did.
